### ISSUE TITLE
Twitter account tracking

### ISSUE THREAD

**Issue by crookm** [Bloometa/Bloometa-WebApp#6]
Allow Twitter accounts to be tracked over time, just like how the Instagram account service is currently setup now.

This should be done through the Twitter API ([user lookup endpoint](http://bit.ly/2sXyLg5)). Each request can have up to 100 lookups, with a maximum of 300 requests per 15 minutes - something to consider with the web job.

## Acceptance criteria
- [x] Users should be able to add Twitter accounts to track
- [x] Users should be able to track the follower history of accounts since they have been added
- [x] Accounts should be verified for existence before being added into the system
